Submitted by: Sameer Dahal

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [ ]:
import numpy as np
import time

Problem - 1: Array Creation:

In [ ]:
# 1) Empty 2x2 array
empty_2x2 = np.empty((2, 2))
print("1) Empty 2x2:\n", empty_2x2)

# 2) All ones array 4x2
ones_4x2 = np.ones((4, 2))
print("\n2) Ones 4x2:\n", ones_4x2)

# 3) Array filled with a value
filled = np.full((3, 4), 7)  # example shape 3x4, fill with 7
print("\n3) Filled array (3x4) with 7:\n", filled)

# 4) Zeros array same shape as a given array
given = np.array([[1.5, 2.5], [3.5, 4.5]])
zeros_like_given = np.zeros_like(given)
print("\n4) Zeros like given:\n", zeros_like_given)

# 5) Ones array same shape as a given array
ones_like_given = np.ones_like(given)
print("\n5) Ones like given:\n", ones_like_given)

# 6) Convert list to numpy array
new_list = [1, 2, 3, 4]
converted = np.array(new_list)
print("\n6) Converted list to np array:\n", converted)

1) Empty 2x2:
 [[1.11965304e-315 0.00000000e+000]
 [4.94065646e-324 6.61121294e-310]]

2) Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3) Filled array (3x4) with 7:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

4) Zeros like given:
 [[0. 0.]
 [0. 0.]]

5) Ones like given:
 [[1. 1.]
 [1. 1.]]

6) Converted list to np array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
# 1) Array from 10 to 49
arr_10_49 = np.arange(10, 50)
print("1) Array 10–49:\n", arr_10_49)

# 2) 3x3 matrix 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2) 3x3 matrix 0–8:\n", matrix_3x3)

# 3) Identity matrix 3x3
I3 = np.eye(3)
print("\n3) Identity 3x3:\n", I3)

# 4) Random array of size 30 + mean
r30 = np.random.random(30)
print("\n4) Random 30 array:\n", r30)
print("Mean:", r30.mean())

# 5) 10x10 random array min, max
r10 = np.random.random((10, 10))
print("\n5) Random 10x10:\n", r10)
print("Min:", r10.min(), "Max:", r10.max())

# 6) Zero array size 10, replace 5th element with 1
z10 = np.zeros(10)
z10[4] = 1
print("\n6) Replace 5th with 1:\n", z10)

# 7) Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
rev = arr[::-1]
print("\n7) Reversed array:\n", rev)

# 8) Border 1s, inside 0s (example 5x5)
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print("\n8) Border ones, inside zeros:\n", border)

# 9) 8x8 checkerboard
chk = np.zeros((8, 8), dtype=int)
chk[1::2, ::2] = 1
chk[::2, 1::2] = 1
print("\n9) Checkerboard pattern:\n", chk)

1) Array 10–49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2) 3x3 matrix 0–8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3) Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4) Random 30 array:
 [0.88849345 0.98043541 0.20814817 0.6877808  0.75001767 0.10981259
 0.89774671 0.36690058 0.37179081 0.02357085 0.30607164 0.9725377
 0.1577754  0.51323739 0.39149218 0.09926985 0.61968323 0.09405991
 0.00720407 0.58507174 0.25063934 0.46228381 0.55420169 0.5063017
 0.97923994 0.35894143 0.20178214 0.12721707 0.68678754 0.86385974]
Mean: 0.4674118187186615

5) Random 10x10:
 [[0.64761174 0.3263339  0.84704424 0.67713086 0.94177927 0.66608933
  0.44745017 0.53097899 0.53960129 0.05840603]
 [0.02839334 0.91043202 0.66777589 0.80421593 0.24873287 0.44981191
  0.28991627 0.17895166 0.34818965 0.333618  ]
 [0.95563991 0.08065372 0.78913276 0.62711472 0.94284794 0.98957774
  0.5097559  0.73061867 0.28946135 0.67466506]
 [0.026960

Problem - 3: Array Operations:

In [ ]:
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 1) Add
print("1) x + y:\n", x + y)

# 2) Subtract
print("\n2) x - y:\n", x - y)

# 3) Multiply with integers
print("\n3) x * 3:\n", x * 3)
print("y * 2:\n", y * 2)

# 4) Square elements
print("\n4) x squared:\n", x ** 2)

# 5) Dot products
print("\n5a) v·w =", np.dot(v, w))
print("5b) x·v:\n", x.dot(v))
print("5c) x·y:\n", x.dot(y))

# 6) Concatenate
xy_concat = np.concatenate((x, y), axis=0)
print("\n6a) x & y row concat:\n", xy_concat)

vw_concat = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\n6b) v & w column concat:\n", vw_concat)

# 7) Try concatenating x and v
try:
    bad = np.concatenate((x, v))
except Exception as e:
    print("\n7) Error concatenating x and v:\n", e)
    print("Reason: x is 2D with shape", x.shape,
          "but v is 1D with shape", v.shape)


1) x + y:
 [[ 6  8]
 [10 13]]

2) x - y:
 [[-4 -4]
 [-4 -3]]

3) x * 3:
 [[ 3  6]
 [ 9 15]]
y * 2:
 [[10 12]
 [14 16]]

4) x squared:
 [[ 1  4]
 [ 9 25]]

5a) v·w = 219
5b) x·v:
 [29 77]
5c) x·y:
 [[19 22]
 [50 58]]

6a) x & y row concat:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

6b) v & w column concat:
 [[ 9 11]
 [10 12]]

7) Error concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D with shape (2, 2) but v is 1D with shape (2,)


Problem - 4: Matrix Operations:

In [ ]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

# 1) A * A^-1 = I
A_inv = np.linalg.inv(A)
print("1) A @ A_inv:\n", A @ A_inv)

# 2) AB != BA
print("\n2) AB:\n", A @ B)
print("BA:\n", B @ A)
print("Equal?", np.allclose(A @ B, B @ A))

# 3) (AB)^T = B^T A^T
left = (A @ B).T
right = B.T @ A.T
print("\n3) (AB)^T:\n", left)
print("B^T A^T:\n", right)
print("Equal?", np.allclose(left, right))


1) A @ A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2) AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Equal? False

3) (AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Equal? True


 Linear equation using Inverse Methods

In [ ]:
A_sys = np.array([
    [ 2, -3,  1],
    [ 1, -1,  2],
    [ 3,  1, -1]
])

B_sys = np.array([-1, -3, 9])

# Using inverse
X_inv = np.linalg.inv(A_sys) @ B_sys
print("Solution using inverse:\n", X_inv)

# Using solve()
X_solve = np.linalg.solve(A_sys, B_sys)
print("\nSolution using np.linalg.solve:\n", X_solve)

Solution using inverse:
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?

Experiment: Python Lists vs NumPy Speed

In [ ]:
N = 1_000_000

# Prepare lists and numpy arrays
list1 = list(range(N))
list2 = list(range(N))

arr1 = np.array(list1)
arr2 = np.array(list2)

# 1) Element-wise addition
start = time.time()
list_add = [list1[i] + list2[i] for i in range(N)]
print("List addition time:", time.time() - start)

start = time.time()
np_add = arr1 + arr2
print("NumPy addition time:", time.time() - start)

# 2) Element-wise multiplication
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(N)]
print("\nList multiplication time:", time.time() - start)

start = time.time()
np_mul = arr1 * arr2
print("NumPy multiplication time:", time.time() - start)

# 3) Dot product
start = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(N))
print("\nList dot product time:", time.time() - start)

start = time.time()
np_dot = np.dot(arr1, arr2)
print("NumPy dot product time:", time.time() - start)

List addition time: 0.10315823554992676
NumPy addition time: 0.004784107208251953

List multiplication time: 0.1079397201538086
NumPy multiplication time: 0.004773139953613281

List dot product time: 0.09822654724121094
NumPy dot product time: 0.002016782760620117


Matrix Multiplication Test (1000×1000)

In [10]:
size = 1000

# Python list matrices
M1_list = [[1]*size for _ in range(size)]
M2_list = [[1]*size for _ in range(size)]

# NumPy matrices
M1_np = np.ones((size, size))
M2_np = np.ones((size, size))

# Python list matrix multiplication
start = time.time()
M_res_list = [[sum(M1_list[i][k] * M2_list[k][j] for k in range(size))
               for j in range(size)]
              for i in range(size)]
print("List matrix multiplication time:", time.time() - start)

# NumPy matrix multiplication
start = time.time()
M_res_np = M1_np @ M2_np
print("NumPy matrix multiplication time:", time.time() - start)

List matrix multiplication time: 114.4952220916748
NumPy matrix multiplication time: 0.05406975746154785
